development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username: cathycullen
  password: cullen1

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: cathycullen
  password: cullen1
